apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-data-protection-test-onboarding-service-deployment
spec:
  selector:
    matchLabels:
      app: cloud-data-protection-test-onboarding-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-data-protection-test-onboarding-app
    spec:
      containers:
        - name: cloud-data-protection-onboarding-service
          image: cdpregistrytest.azurecr.io/clouddataprotection:cdp_onboarding_service
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Test"
            - name: CDP_DEV_ONBOARDING_GOOGLE_OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cdp-onboarding-google-oauth2-client-id
                  key: value
            - name: CDP_DEV_ONBOARDING_GOOGLE_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cdp-onboarding-google-oauth2-client-secret
                  key: value
            - name: CDP_PAPERTRAIL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cdp-papertrail-access-token
                  key: value
            - name: CDP_PAPERTRAIL_URL
              valueFrom:
                secretKeyRef:
                  name: cdp-papertrail-url
                  key: value
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 5021

---

apiVersion: v1
kind: Service
metadata:
  name: onboarding-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: cloud-data-protection-test-onboarding-app
  ports:
  - protocol: TCP
    targetPort: 5021
    port: 80
