apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-data-protection-test-backend
  labels:
    app: cloud-data-protection-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-data-protection-test
  template:
    metadata:
      labels:
        app: cloud-data-protection-test
    spec:
      containers:
      - name: cloud-data-protection-gateway
        image: cdpregistrytest.azurecr.io/clouddataprotection:cdp_gateway
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        - name: CDP_BACKUP_DEMO_FUNCTIONS_KEY
          valueFrom:
            secretKeyRef:
              name: cdp-backup-demo-api-key
              key: value
        - name: CDP_PAPERTRAIL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cdp-papertrail-access-token
              key: value
        - name: CDP_PAPERTRAIL_URL
          valueFrom:
            secretKeyRef:
              name: cdp-papertrail-url
              key: value
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 5001
      - name: cloud-data-protection-onboarding-service
        image: cdpregistrytest.azurecr.io/clouddataprotection:cdp_onboarding_service
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        - name: CDP_DEV_ONBOARDING_GOOGLE_OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: cdp-onboarding-google-oauth2-client-id
              key: value
        - name: CDP_DEV_ONBOARDING_GOOGLE_OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: cdp-onboarding-google-oauth2-client-secret
              key: value
        - name: CDP_PAPERTRAIL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cdp-papertrail-access-token
              key: value
        - name: CDP_PAPERTRAIL_URL
          valueFrom:
            secretKeyRef:
              name: cdp-papertrail-url
              key: value
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 5021
      - name: cloud-data-protection-backup-config-service
        image: cdpregistrytest.azurecr.io/clouddataprotection:cdp_backup_config_service
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        - name: CDP_PAPERTRAIL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cdp-papertrail-access-token
              key: value
        - name: CDP_PAPERTRAIL_URL
          valueFrom:
            secretKeyRef:
              name: cdp-papertrail-url
              key: value
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 5031
      - name: cloud-data-protection-mail-service
        image: cdpregistrytest.azurecr.io/clouddataprotection:cdp_mail_service
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        - name: CDP_DEV_SENDGRID
          valueFrom:
            secretKeyRef:
              name: cdp-sendgrid
              key: value
        - name: CDP_DEV_SENDGRID_SENDER
          valueFrom:
            secretKeyRef:
              name: cdp-sendgrid-sender
              key: value
        - name: CDP_PAPERTRAIL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cdp-papertrail-access-token
              key: value
        - name: CDP_PAPERTRAIL_URL
          valueFrom:
            secretKeyRef:
              name: cdp-papertrail-url
              key: value
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 5051
